### ISSUE TITLE
Demonstrate how to call another REST service

### ISSUE THREAD

**Issue by GalateaRaj** [galatea-associates/fuse-starter-java#23]
We need to decide if we like spring rest template or feign and show an example of that.

**Comment by gala-dan** [comment]
[Link](https://spring.io/blog/2015/01/20/microservice-registration-and-discovery-with-spring-cloud-and-netflix-s-eureka) to help the mere mortals among us to show differences.

**Comment by gala-dan** [comment]
Also, a very useful [blog](http://theblasfrompas.blogspot.co.uk/2016/12/spring-boot-feign-client-accessing.html) on how to use Feign to consume another REST service, which includes some config settings that are not easily found in other blogs and tutorials.

**Comment by paulo-reichert** [comment]
I believe we like Feign over spring rest template and a good example of how to use it is available in `SettlementRestControllerIntegrationTest.java.`

**Comment by GalateaEric** [comment]
STEERCO DECISION: yes, feign for external rest services is the recommended approach.

**Comment by GalateaEric** [comment]
this issue should remain open until there is an example of WireMock-ing the external service in an automated test

**Comment by GalateaFarhaad** [comment]
I don't think the Feign example inside `SettlementRestControllerIntegrationTest.java` is an appropriate example - it just uses some `Feign.builder()` functionality inside of a test method to call our own rest service. A better example would probably have a `@FeignClient` interface within the actual code calling an external REST service.
Is there a specific service we would want to call for this example?

**Comment by GalateaFarhaad** [comment]
The IEX API for stock data looks like a good option. No API key is needed, so we wouldn't have to deal with registration, maintaining an API key, or rate limits. https://iextrading.com/developer/docs/ 

Some other options are:
- AlphaVantage (https://www.alphavantage.co/)
  - Current and historical stock data, FX data
  - Requires API key (free registration), requests limited to 5/min and 500/day
- Exchangeratesapi.io (https://exchangeratesapi.io/)
  - FX data
  - No API key

Big list of some free public APIs: https://github.com/public-apis/public-apis

**Comment by GalateaEric** [comment]
I've added WireMock to use for the IEX service unit tests.  Waiting on Jenkins to be back to functional before adding some integration tests.  Outside of the integration tests the feature/23-demonstrate-rest-call-with-feign branch is about ready to merge.

**Comment by GalateaEric** [comment]
some outcome from the steerco discussion of this branch...

1) replace the manually created file stubs by whatever output is generated when the WireMock proxy mode recorder something is used instead.  Need to figure out how to run that against the IEX end points.

2) if we're not going to use all of spring cloud contract we should instead import WireMock stand alone rather than use the <artifactId>spring-cloud-starter-contract-stub-runner</artifactId> import.  This will probably require some subtle changes to the unit test class that sets up the wire mock.

**Comment by GalateaRaj** [comment]
I would add:

3.  Utilize rest assured to test the entire servlet stack and validate json response

**Comment by GalateaEric** [comment]
#287 raised to capture the REST assured thing.  I would prefer to migrate all the different rest controller unit tests to rest assured at once, rather than have some on rest assured and some on MockMvc.  I'll leave MockMvc in place on the IEX endpoints for now for consistency's sake, and to be able to actually get something into develop before each request snowballs out of control and nothing ever gets merged before people roll off fuse.

**Comment by GalaHarley** [comment]
Followed the instructions at http://wiremock.org/docs/record-playback/ to generate JSON stubs for 

> 1. replace the manually created file stubs by whatever output is generated when the WireMock proxy mode recorder something is used instead.  Need to figure out how to run that against the IEX end points.

**Comment by GalateaEric** [comment]
this is merged to develop.  Closing.
