### ISSUE TITLE
REST tracer doesn't populate request-success correctly on 400 status codes

### ISSUE THREAD

**Issue by GalateaRaj** [galatea-associates/fuse-starter-java#40]
This includes serialization errors or bad urls.

Request-success is set to "true" instead of "false".

**Comment by Gala-Sortino** [comment]
From looking into this issue, there seem to be multiple things at fault here.

The Request-success result is determined within Tracer.java, inside the runAndTraceSuccess function. Here the success is determined by whether or not an exception occurs.

However, due to the way in which exceptions are handled within the RestExceptionHandler, no exceptions would be passed back to the func call.

Also following on from this, exceptions such as "MissingServletRequestParameterException" are silently ignored if an exception handler is not present, thus not causing the success to still remain true.

A potential solution could involve inspecting the returned result of the func call, to see if an error occurred or not.

**Comment by GalateaEric** [comment]
in FuseWebRequestTraceFilter (section below).

In the try {} block add a check against the response code and sets the request-success variable to false.



      try {
        t.runAndTraceSuccess("request", () -> {
          filterChain.doFilter(request, response);
          status.setValue(response.getStatus());
          return Void.TYPE;
        });
      } finally {
        enhanceTrace(springTraceInfo, request, status.intValue() == response.getStatus() ? response
            : new CustomStatusResponseWrapper(response, status.intValue()));
        addAuditHeaders(response);
        updateResponse(response);
      }
